import {money,normalizeLife,JOBS,wage,shiftBrief,HOMES,FURNISHINGS,CLUB_SCENES} from './life.js';
import {escapeHTML as e,workArt} from './expansion-ui.js';
const btn=(text,attrs='')=>`<button ${attrs}>${text}</button>`;
export function homeIllustration(h,items=[]) {
 return `<svg viewBox='0 0 520 290' role='img' aria-label='${e(h.name)} interior illustration'><rect width='520' height='290' fill='#e5d5b9'/><path d='M0 212L200 159L520 212V290H0' fill='#a88967'/><path d='M200 0V159L520 212V0' fill='#ccc9b2'/><rect x='258' y='25' width='147' height='111' fill='#405361'/><path d='M332 25V136M258 81H405' stroke='#efe4c9' stroke-width='8'/><circle cx='371' cy='53' r='14' fill='#edd6a2'/><path d='M270 130V86H290V130H310V65H327V130H350V94H385V130' fill='#243d48'/><path d='M85 238L264 185L435 226L256 283Z' fill='${h.color}'/><path d='M23 173L131 144L216 171V230L104 263L23 229Z' fill='#725344'/><path d='M27 176L129 150L210 176L105 207Z' fill='#efe4ca'/><path d='M105 207L210 176V218L105 251Z' fill='${h.color}'/><path d='M35 171L82 159L115 172L66 188Z' fill='#faf0d6'/><path d='M341 181L443 165L492 185L389 208Z' fill='#705e48'/><path d='M353 185V241M481 185V234' stroke='#705e48' stroke-width='8'/><rect x='32' y='43' width='83' height='68' fill='#947558'/><rect x='39' y='50' width='69' height='54' fill='${h.color}'/><path d='M45 96L67 62L98 96' fill='#ead8ac'/>${items.includes('plant')?`<path d='M440 243L451 265H478L487 240Z' fill='#9b654d'/><path d='M465 242V173' stroke='#42704e' stroke-width='5'/><g fill='#527d58'><ellipse cx='451' cy='191' rx='18' ry='10'/><ellipse cx='477' cy='210' rx='18' ry='10'/></g>`:''}${items.includes('lamp')?`<path d='M380 125L400 157H358Z' fill='#f8db9b'/><path d='M380 156V180' stroke='#ad8a50' stroke-width='4'/>`:''}<text x='473' y='38' text-anchor='middle' fill='#f1e5cb' font-family='Georgia' font-size='24'>${h.number}</text></svg>`;
}
export function createLifeUI(hooks={}) {
 const root=document.createElement('section');root.className='shop-overlay life-overlay';root.hidden=true;root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','Life on 47th');document.body.append(root);
 let state=normalizeLife(),page='wallet',context={},notice='',picks=[null,null,null],prior=null;
 const close=()=>{root.hidden=true;document.getElementById('visor').inert=false;prior?.focus?.();};
 const exit=()=>{close();hooks.onClose?.();};
 function apply(r){if(!r)return;state=normalizeLife(r.state);notice=r.message||'';if(r.ok)picks=[null,null,null];render();}
 function nav(id){close();hooks.onNavigate?.(id);}
 function render(){
  const focus=root.querySelector(':focus')?.dataset.focus,scroll=root.querySelector('.shop-scroll')?.scrollTop||0;
  root.classList.toggle('life-working',page==='jobs'&&!!state.active&&context.job===state.active.job);
  root.innerHTML=`<div class='shop-sheet life-sheet'><header class='shop-mast'><span>47TH STREET · MAKE YOURSELF AT HOME</span>${btn('CLOSE ×',`data-close data-focus='close' class='shop-close'`)}</header><div class='shop-scroll'><div class='life-heading'><div><p class='shop-eyebrow'>A LITTLE WORK. A PLACE OF YOUR OWN.</p><h1>Life on 47th.</h1></div><div class='life-balance'><small>YOUR WALLET</small><strong>${money(state.wallet)}</strong><span>IN-GAME DOLLARS</span></div></div><nav class='life-tabs' aria-label='Life sections'>${['wallet','jobs','homes','club'].map(t=>btn(t==='homes'?'MY HOME':t.toUpperCase(),`data-page='${t}' data-focus='page-${t}' aria-current='${page===t?'page':'false'}'`)).join('')}</nav><div class='life-content'>${page==='jobs'?jobs():page==='homes'?homes():page==='club'?club():wallet()}</div><p class='life-feedback' role='status' aria-live='polite'>${e(notice)}</p></div><footer class='shop-foot'><span>Cash, keys and keepsakes stay with you across nights.</span><span>ASTORIA / 47TH STREET</span></footer></div>`;
  root.querySelector('[data-close]').onclick=exit;
  root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;notice='';picks=[null,null,null];render();root.querySelector(`[data-page='${page}']`).focus();});
  root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
  root.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>apply(hooks.onStart?.(b.dataset.job)));
  root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{picks[+b.dataset.step]=+b.dataset.pick;render();if(state.active.job==='club')hooks.onNote?.(+b.dataset.pick);});
  root.querySelector('[data-serve]')?.addEventListener('click',()=>{const a=state.active;apply(hooks.onSubmit?.(picks,`${a.serial}:${a.order}:${a.job}`));});
  root.querySelectorAll('[data-buy-home]').forEach(b=>b.onclick=()=>apply(hooks.onBuyHome?.(b.dataset.buyHome)));
  root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>apply(hooks.onAction?.(b.dataset.action,b.dataset.id)));
  root.querySelector('.shop-scroll').scrollTop=scroll;
  (root.querySelector(`[data-focus='${focus}']:not(:disabled)`)||root.querySelector(`[data-page='${page}']`)).focus({preventScroll:true});
 }
 function wallet(){const goal=HOMES.find(h=>h.id===state.goal),percent=Math.min(100,Math.floor(state.wallet/goal.price*100));return `<div class='life-wallet-grid'><article class='life-goal'><p class='shop-eyebrow'>${state.properties.includes(goal.id)?'YOU HAVE THE KEYS':'SAVING FOR SOMETHING GOOD'}</p>${homeIllustration(goal,state.installed)}<h2>${e(goal.name)}</h2><p>${e(goal.tag)}</p><div class='savings-line'><strong>${money(Math.min(state.wallet,goal.price))}</strong><span>of ${money(goal.price)}</span></div><progress max='100' value='${percent}' aria-label='Apartment savings'>${percent}%</progress>${btn('VIEW APARTMENTS ↗',`data-page='homes' data-focus='homes-link'`)}</article><div><div class='life-stats'><article><small>TOTAL EARNED</small><strong>${money(state.earned)}</strong></article><article><small>SHIFTS FINISHED</small><strong>${state.shifts}</strong></article></div><article class='life-advice'><h2>Your first key is closer than it looks.</h2><p>Help behind a counter for a $20 nightly thank-you. Take a paid shift: three customer orders earn $45–$65. Jobs never run out.</p><p>Browse homewares in every shop. They’re stored safely until you have a home.</p>${btn(state.active?'RESUME MY SHIFT ↗':'FIND A JOB ↗',`data-page='jobs' data-focus='jobs-link'`)}</article><div class='life-ledger'><p class='shop-eyebrow'>RECENT RECEIPTS</p>${[...state.ledger].reverse().slice(0,8).map(l=>`<p><span>${e(l.label)}</span><strong class='${l.amount>0?'income':''}'>${l.amount>0?'+':'−'}${money(Math.abs(l.amount))}</strong></p>`).join('')||'<p><span>Your $120 welcome envelope is in your wallet.</span></p>'}</div></div></div>`;}
 function jobs(){const a=state.active,b=shiftBrief(state),canWork=a&&context.job===a.job;
  if(canWork)return `<div class='shift-banner'><div><small>CLOCKED IN · ${e(b.owner)}</small><h2>${e(b.title)}</h2></div><strong>${money(wage(state,a.job))}<small>ON COMPLETION</small></strong></div><div class='shift-progress'>${[0,1,2].map(i=>`<span class='${i<=a.order?'current':''}'>${i<a.order?'✓':i+1} ${i<a.order?'FILED':'ORDER'}</span>`).join('')}</div><div class='paid-work'><div class='paid-work-art'>${workArt(b,picks)}<div class='order-slip'><small>CUSTOMER ORDER ${a.order+1} OF 3</small><h3>Please put together…</h3>${b.recipe.map((n,i)=>`<p><b>${i+1}.</b> ${e(b.steps[i][1][n])}</p>`).join('')}</div></div><div>${b.steps.map((step,i)=>`<fieldset><legend>${e(step[0])}</legend>${step[1].map((label,n)=>btn(e(label),`data-step='${i}' data-pick='${n}' data-focus='pick-${i}-${n}' aria-pressed='${picks[i]===n}'`)).join('')}</fieldset>`).join('')}${btn(a.order===2?'FINISH SHIFT & COLLECT PAY ↗':'SERVE CUSTOMER ↗',`data-serve data-focus='serve' class='life-primary' ${picks.includes(null)?'disabled':''}`)}<p class='life-muted'>No timer. Close this panel and resume the same order later.</p></div></div>`;
  return `<div class='life-section-title'><div><p class='shop-eyebrow'>THE BLOCK IS HIRING</p><h2>A good night’s work.</h2><p>Three orders per shift. A $5 raise after 3 and 6 shifts with the same employer.</p></div></div>${a?`<div class='shift-resume'><strong>${e(JOBS.find(j=>j.id===a.job).owner)} is holding your shift · ${a.order}/3 orders filed.</strong>${btn('MARK MY WORKPLACE ↗',`data-go='${a.job==='club'?'clubdesk':a.job}'`)}</div>`:''}<div class='jobs-grid'>${JOBS.map(j=>`<article class='job-card'><small>${e(j.owner)} · ${state.experience[j.id]>=6?'SENIOR':state.experience[j.id]>=3?'REGULAR':'NEW STARTER'}</small><h3>${e(j.name)}</h3><p><strong>${money(wage(state,j.id))}</strong> / shift · ${state.experience[j.id]} completed</p>${context.job===j.id?btn('CLOCK IN ↗',`data-job='${j.id}' data-focus='job-${j.id}' ${a?'disabled':''}`):btn('FIND THE WORKPLACE ↗',`data-go='${j.id==='club'?'clubdesk':j.id}'`)}</article>`).join('')}</div>`;
 }
 function homes(){return `<div class='life-section-title'><div><p class='shop-eyebrow'>HOMES ON 47TH · ASTORIA &amp; MERCER ROW</p><h2>A key with your name on it.</h2><p>One purchase, yours to keep. Find Mercer Row opposite Mercer Garden, or climb Astoria’s east stairs to 2F. No rent or upkeep.</p></div><div>${btn('MERCER ROW LISTINGS ↗',`data-go='parkproperty'`)}${btn('ASTORIA PROPERTY DESK ↗',`data-go='property'`)}</div></div><div class='home-grid'>${HOMES.map(h=>{const owned=state.properties.includes(h.id);return `<article class='home-card ${state.home===h.id?'active-home':''}'>${homeIllustration(h,state.home===h.id?state.installed:[])}<div><small>${h.number} · ${e(h.location||'Astoria · upstairs on 2F')} · ${owned?'KEYS COLLECTED':'FURNISHED APARTMENT'}</small><h3>${e(h.name)}</h3><p>${e(h.detail)}</p>${h.floorY===0?`<p>Entrance from 47th Street · opposite Mercer Garden</p>${btn('FIND THIS BUILDING ↗',`data-go='parkproperty'`)}`:''}<strong class='home-price'>${owned?(state.home===h.id?'YOUR HOME':'OWNED'):money(h.price)}</strong><div class='home-actions'>${owned?`${btn('FIND MY FRONT DOOR ↗',`data-go='home-${h.id}'`)}${state.home!==h.id?btn('MAKE THIS HOME',`data-action='home' data-id='${h.id}' data-focus='home-${h.id}'`):''}`:`${btn(state.wallet>=h.price?'BUY APARTMENT · '+money(h.price):'NEED '+money(h.price-state.wallet)+' MORE',`data-buy-home='${h.id}' data-focus='buy-${h.id}' ${state.wallet<h.price?'disabled':''}`)}${btn(state.goal===h.id?'SAVINGS GOAL ✓':'SAVE TOWARD THIS',`data-action='goal' data-id='${h.id}' data-focus='goal-${h.id}'`)}`}</div></div></article>`;}).join('')}</div><div class='life-section-title'><div><p class='shop-eyebrow'>DELIVERED BY YOUR NEIGHBORS</p><h2>Make it feel like you.</h2><p>Furnishings follow your active home. Switch them on or store them below.</p></div></div><div class='furnishing-list'>${FURNISHINGS.map(i=>`<article><span style='color:${i.color}'>${i.icon}</span><div><h3>${e(i.name)}</h3><p>${state.furnishings.includes(i.id)?state.installed.includes(i.id)?state.home?'Installed in your home':'Ready for your first home':'In storage':`${money(i.price)} · available at ${i.shop}`}</p></div>${state.furnishings.includes(i.id)?btn(state.installed.includes(i.id)?'STORE':'INSTALL',`data-action='furnish' data-id='${i.id}' data-focus='furnish-${i.id}'`):btn('FIND SHOP ↗',`data-go='${i.shop}'`)}</article>`).join('')}</div>`;}
 function club(){return `<div class='club-showcase'><div class='club-orbit'><span>47</span><i></i><i></i><i></i></div><div><p class='shop-eyebrow'>THE HOUSE HAS RANGE</p><h2>Set the mood.<br>Make the room yours.</h2><p>Choose a palette for the actual dance floor, overhead washes and laser beams. Take soundcheck shifts at the console beside the DJ booth.</p>${btn('FIND THE LIGHTING DESK ↗',`data-go='clubdesk'`)}</div></div><div class='scene-grid'>${CLUB_SCENES.map(s=>`<article style='--scene:${s.color};--accent:${s.accent}' class='scene-card'><div class='scene-swatch'><span></span><span></span><span></span></div><h3>${s.name}</h3><p>${s.description}</p>${btn(state.scene===s.id?'PLAYING IN THE ROOM ✓':s.premium&&!state.patron?'PATRON PASS REQUIRED':'SET THIS SCENE ↗',`data-action='scene' data-id='${s.id}' data-focus='scene-${s.id}' ${s.premium&&!state.patron?'disabled':''}`)}</article>`).join('')}</div><div class='club-pass'><div><small>THE 47TH PATRON CARD</small><h3>${state.patron?'Your name is on the card.':'A little love for the house.'}</h3><p>A permanent $60 patron pass unlocks Emerald afterparty.</p></div>${state.patron?'<strong>PATRON ✓</strong>':btn(state.wallet>=60?'BUY PATRON PASS · $60':'NEED '+money(60-state.wallet)+' MORE',`data-action='patron' data-focus='patron' ${state.wallet<60?'disabled':''}`)}</div>`;}
 root.addEventListener('keydown',ev=>{if(ev.key==='Escape'){ev.preventDefault();exit();}if(ev.key==='Tab'){const all=[...root.querySelectorAll('button:not(:disabled)')],first=all[0],last=all.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}}ev.stopPropagation();});root.addEventListener('keyup',ev=>ev.stopPropagation());
 return {open(input,section='wallet',ctx={}){prior=document.activeElement;state=normalizeLife(input);page=section;context=ctx;notice='';picks=[null,null,null];root.hidden=false;document.getElementById('visor').inert=true;render();root.querySelector('[data-close]').focus();},close,get isOpen(){return !root.hidden;}};
}
