import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
const url=process.env.VIBE_TEST_URL||'http://127.0.0.1:8000',session=process.env.VIBE_TEST_SESSION||'vibe-life',output=process.env.VIBE_TEST_OUTPUT||'/tmp/vibe-check-life';mkdirSync(output,{recursive:true});
const cli=(...args)=>execFileSync('npx',['--yes','agent-browser@0.37.1','--session',session,...args],{encoding:'utf8',timeout:60000});
const ev=s=>JSON.parse(cli('eval',s).trim()),shot=n=>cli('screenshot',`${output}/${n}.png`),state=()=>ev('window.__vibeInspect.snapshot()'),reports=[];
function check(n,fn){fn();reports.push(n);console.log('ok  '+n);}
function helpers(){ev(`(async()=>{const {shiftBrief}=await import('./js/life.js');const frames=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));window.lifeTest={
 key(key){window.dispatchEvent(new KeyboardEvent('keydown',{key}));window.dispatchEvent(new KeyboardEvent('keyup',{key}));},
 async close(){for(const b of document.querySelectorAll('.shop-overlay:not([hidden]) .shop-close'))b.click();document.querySelector('#talk:not(.hidden) #talkClose')?.click();await frames();},
 async place(p){await this.close();window.__vibeInspect.place(...p);await frames();return window.__vibeInspect.snapshot().target;},
 async shop(p){await this.place(p);this.key('e');await frames();if(document.body.dataset.phase==='talk'){document.querySelector('#talkChoices button').click();await frames();}if(document.body.dataset.phase!=='shop')throw Error('No shop: '+window.__vibeInspect.snapshot().target);},
 async job(p){await this.shop(p);document.querySelector('[data-career]').click();document.querySelector('[data-job]:not(:disabled)')?.click();await frames();},
 submit(){const b=shiftBrief(window.__vibeInspect.snapshot().commerce.life);b.recipe.forEach((n,i)=>document.querySelector('.life-overlay [data-step="'+i+'"][data-pick="'+n+'"]').click());document.querySelector('[data-serve]').click();},
 async prop(p){await this.place(p);this.key('e');await frames();if(document.querySelector('.life-overlay').hidden)throw Error('No life panel: '+window.__vibeInspect.snapshot().target);},
 panel(page){document.getElementById('lifeBtn').click();document.querySelector('.life-overlay [data-page="'+page+'"]').click();},frames};return true;})()`);}
const poses={records:[-35.1,33.8,-36.5,33.8],pharmacy:[-23,33.6,-24.2,33.6],florist:[-12.2,35.1,-12.2,36.7],liquor:[24.6,34.8,24.6,36.5],barber:[35.8,34.2,35.9,36.4],rivoli:[6,34,6,35.6],diner:[-28.6,0,-28.6,1.55]};
try{
 cli('open',url+'/?inspect=1');cli('wait','--fn','!!window.__vibeInspect');ev("localStorage.removeItem('vc9k-progress');true");cli('open',url+'/?inspect=1');cli('wait','--fn','!!window.__vibeInspect');cli('errors','--clear');cli('set','viewport','1440','900');cli('find','role','button','click','--name','ENTER THE NIGHT');helpers();
 check('wallet begins with a welcome envelope and reachable savings goal',()=>{ev("lifeTest.panel('wallet');true");assert.equal(state().commerce.life.wallet,120);shot('wallet');});
 check('shops show prices, filters and a separate permanent homewares department',()=>{ev(`lifeTest.shop(${JSON.stringify(poses.records)})`);shot('records-catalog');ev("document.querySelector('[data-select=blue-hour]').click();true");assert.equal(state().commerce.life.wallet,112);ev("document.querySelector('[data-filter]').click();true");assert.equal(ev("!!document.querySelector('[data-select=blue-hour]')"),false);ev("document.querySelector('[data-department=home]').click();true");shot('records-homewares');ev("document.querySelector('[data-furnishing=turntable]').click();true");assert.equal(state().commerce.life.wallet,74);assert.deepEqual(state().commerce.life.furnishings,['turntable']);assert.ok(ev("document.querySelector('[data-furnishing=turntable]').disabled"));});
 check('paid shift refuses wrong orders and retains keyboard focus',()=>{ev(`lifeTest.job(${JSON.stringify(poses.records)})`);ev("document.querySelectorAll('.life-overlay [data-pick]').forEach(b=>{if(b.dataset.pick==='0')b.click()});document.querySelector('[data-serve]').click();true");assert.equal(state().commerce.life.wallet,74);ev('lifeTest.submit();true');assert.equal(state().commerce.life.active.order,1);assert.ok(ev("document.querySelector('.life-overlay').contains(document.activeElement)"));shot('paid-record-shift');});
 check('an unfinished shift resumes after reload and pays exactly once',()=>{cli('open',url+'/?inspect=1');cli('wait','--fn','!!window.__vibeInspect');cli('find','role','button','click','--name','ENTER THE NIGHT');helpers();assert.equal(state().commerce.life.active.order,1);ev(`lifeTest.job(${JSON.stringify(poses.records)})`);ev('lifeTest.submit();lifeTest.submit();true');assert.equal(state().commerce.life.wallet,119);assert.equal(state().commerce.life.shifts,1);assert.equal(state().commerce.life.active,null);});
 check('repeatable shifts provide a path to buying an apartment',()=>{for(let i=0;i<2;i++){ev("document.querySelector('[data-job=records]').click();lifeTest.submit();lifeTest.submit();lifeTest.submit();true");}assert.equal(state().commerce.life.wallet,209);assert.equal(state().commerce.life.experience.records,3);});
 check('unowned apartments are physically locked',()=>{ev('lifeTest.place([25.6,-3.3,20.7,-3.3,4.4])');assert.equal(state().homes.studio.locked,true);ev("window.dispatchEvent(new KeyboardEvent('keydown',{key:'w'}));true");cli('wait','1300');ev("window.dispatchEvent(new KeyboardEvent('keyup',{key:'w'}));true");assert.ok(state().position.x>24.5);shot('apartment-door');});
 check('property desk sells an apartment, opens its door and delivers stored furniture',()=>{ev('lifeTest.prop([28.9,10.6,28.9,8.8])');shot('apartment-listings');ev("document.querySelector('[data-buy-home=studio]').click();true");assert.equal(state().commerce.life.wallet,29);assert.equal(state().homes.studio.locked,false);assert.deepEqual(state().homes.studio.furnishings,['turntable']);ev('lifeTest.place([25.6,-3.3,20.7,-3.3,4.4])');ev("window.dispatchEvent(new KeyboardEvent('keydown',{key:'w'}));true");cli('wait','1500');ev("window.dispatchEvent(new KeyboardEvent('keyup',{key:'w'}));true");assert.ok(state().position.x<24,'walk through purchased front door');shot('studio-interior');});
 for(const id of ['pharmacy','florist','liquor','barber','rivoli','diner'])check(id+' offers a distinct paid job and a permanent furnishing',()=>{ev(`lifeTest.job(${JSON.stringify(poses[id])})`);ev('lifeTest.submit();lifeTest.submit();lifeTest.submit();true');assert.equal(state().commerce.life.experience[id],1);ev(`lifeTest.shop(${JSON.stringify(poses[id])})`);ev("document.querySelector('[data-department=home]').click();document.querySelector('[data-furnishing]').click();true");});
 check('seven shop furnishings install together and can be stored again',()=>{assert.equal(state().commerce.life.furnishings.length,7);assert.equal(state().homes.studio.furnishings.length,7);ev("lifeTest.panel('homes');document.querySelector('[data-action=furnish][data-id=lamp]').click();true");assert.equal(state().homes.studio.furnishings.includes('lamp'),false);ev("document.querySelector('[data-action=furnish][data-id=lamp]').click();true");assert.equal(state().homes.studio.furnishings.includes('lamp'),true);shot('my-home');});
 check('club soundcheck pays and the room remembers its lighting scene',()=>{ev('lifeTest.prop([9.9,-6.8,9.9,-9.1])');shot('club-palettes');ev("document.querySelector('[data-action=scene][data-id=blue]').click();document.querySelector('[data-page=jobs]').click();document.querySelector('[data-job=club]').click();true");shot('soundcheck');ev('lifeTest.submit();lifeTest.submit();lifeTest.submit();true');assert.equal(state().commerce.life.experience.club,1);ev("document.querySelector('[data-page=club]').click();document.querySelector('[data-action=patron]').click();document.querySelector('[data-action=scene][data-id=mint]').click();true");assert.equal(state().commerce.life.patron,true);assert.equal(state().commerce.life.scene,'mint');});
 check('mobile home, job and club panels fit without horizontal overflow',()=>{cli('set','viewport','390','844');for(const page of ['homes','jobs','club']){ev(`document.querySelector('[data-page=${page}]').click();true`);assert.equal(ev("document.querySelector('.life-overlay .shop-scroll').scrollWidth<=document.querySelector('.life-overlay .shop-scroll').clientWidth"),true);shot(page+'-mobile');}ev("document.querySelector('[data-page=jobs]').click();document.querySelector('[data-job=club]').click();true");shot('job-mobile');assert.equal(ev("document.querySelector('.life-overlay .shop-scroll').scrollWidth<=document.querySelector('.life-overlay .shop-scroll').clientWidth"),true);ev('lifeTest.submit();lifeTest.submit();lifeTest.submit();true');});
 check('wallet, keys, room fittings and patron scene survive reload',()=>{const before=state().commerce.life;cli('open',url+'/?inspect=1');cli('wait','--fn','!!window.__vibeInspect');cli('find','role','button','click','--name','ENTER THE NIGHT');helpers();assert.deepEqual(state().commerce.life,before);assert.equal(state().homes.studio.locked,false);assert.equal(state().homes.studio.furnishings.length,7);});
 cli('set','viewport','1440','900');
 ev('lifeTest.place([23,-3.3,18.8,-5.7,4.4])');shot('furnished-studio');ev('lifeTest.place([9.9,-6.9,9.9,-9.1])');shot('club-console');ev('lifeTest.place([0,6,0,-8])');shot('emerald-nightclub');
 assert.equal(cli('errors').trim(),'','no unhandled browser errors');writeFileSync(output+'/report.json',JSON.stringify({passed:reports,output},null,2));console.log(`Life journeys passed. Screenshots: ${output}`);
}catch(error){shot('failure');console.error(cli('eval',`({phase:document.body.dataset.phase,target:window.__vibeInspect?.snapshot().target,feedback:document.querySelector('.life-feedback')?.textContent})`));throw error;}finally{cli('close');}
